# Generated by Django 3.1.7 on 2021-03-21 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IpPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_port', models.IntegerField(default=0)),
                ('ip_protocol', models.CharField(max_length=255)),
                ('to_port', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='IpPermissionsEgress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_port', models.IntegerField(default=0)),
                ('ip_protocol', models.CharField(max_length=255)),
                ('to_port', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='SecurityGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('owner_id', models.IntegerField(default=0)),
                ('group_id', models.CharField(max_length=255)),
                ('vpc_id', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='UserIdGroupPairsEgress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_id', models.CharField(max_length=255)),
                ('user_id', models.IntegerField(default=0)),
                ('permissions_egress', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_id_group_pairs_egress', to='core.ippermissionsegress')),
            ],
        ),
        migrations.CreateModel(
            name='UserIdGroupPairs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_id', models.CharField(max_length=255)),
                ('group_name', models.CharField(max_length=255)),
                ('user_id', models.IntegerField(default=0)),
                ('permission', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_id_group_pairs', to='core.ippermissions')),
            ],
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255)),
                ('value', models.CharField(max_length=255)),
                ('security_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='core.securitygroup')),
            ],
        ),
        migrations.CreateModel(
            name='PrefixListIdsEgress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix_id', models.CharField(max_length=255)),
                ('ip_permissions', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prefix_list_ids_egress', to='core.ippermissionsegress')),
            ],
        ),
        migrations.CreateModel(
            name='PrefixListIds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix_id', models.CharField(max_length=255)),
                ('ip_permissions', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prefix_list_ids', to='core.ippermissions')),
            ],
        ),
        migrations.CreateModel(
            name='Ipv6RangesEgress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ipv6_range', models.CharField(max_length=255)),
                ('ip_permissions', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ipv6_ranges', to='core.ippermissionsegress')),
            ],
        ),
        migrations.CreateModel(
            name='Ipv6Ranges',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ipv6_range', models.CharField(max_length=255)),
                ('ip_permissions', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ipv6_ranges', to='core.ippermissions')),
            ],
        ),
        migrations.CreateModel(
            name='IpRangesEgress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_range', models.CharField(max_length=255)),
                ('ip_permissions', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ip_ranges_egress', to='core.ippermissionsegress')),
            ],
        ),
        migrations.CreateModel(
            name='IpRanges',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_range', models.CharField(max_length=255)),
                ('ip_permissions', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ip_ranges', to='core.ippermissions')),
            ],
        ),
        migrations.AddField(
            model_name='ippermissionsegress',
            name='security_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ip_permissions_egress', to='core.securitygroup'),
        ),
        migrations.AddField(
            model_name='ippermissions',
            name='security_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ip_permissions', to='core.securitygroup'),
        ),
    ]
